from __future__ import annotations

from pathlib import Path
from typing import Dict, List


def _sanitize_stage_name(stage_name: str) -> str:
    return "".join(ch if ch.isalnum() or ch in ("_", "-", ".") else "_" for ch in stage_name)


def stage_log_path(logs_dir: Path, stage_name: str) -> Path:
    logs_dir.mkdir(parents=True, exist_ok=True)
    return logs_dir / f"{_sanitize_stage_name(stage_name)}.log"


def write_commands_ps1(path: Path, command_blocks: List[Dict[str, str]]) -> None:
    lines: List[str] = []
    lines.append("# Auto-generated by codex_reports orchestrator")
    lines.append("$ErrorActionPreference='Stop'")
    lines.append("")
    for block in command_blocks:
        lines.append(f"# Stage: {block['stage']}")
        lines.append(f"# Status: {block['status']}")
        lines.append(block["command"])
        lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    # Use UTF-8 BOM for better compatibility with Windows PowerShell 5 non-ASCII paths.
    path.write_text("\n".join(lines), encoding="utf-8-sig")
